### ISSUE TITLE
Test _salmon_kallisto_mtx_to_10x 0.0.1+galaxy5

### ISSUE THREAD

**Issue by jennaj** [mvdbeek/usegalaxy-tests#34]
Reported in a bug email

```
Traceback (most recent call last):
  File "/cvmfs/main.galaxyproject.org/shed_tools/toolshed.g2.bx.psu.edu/repos/ebi-gxa/salmon_kallisto_mtx_to_10x/e42c217a450f/salmon_kallisto_mtx_to_10x/salmonKallistoMtxTo10x.py", line 71, in <module>
    mmwrite('%s/matrix.mtx' % mtx_out, umi_counts.transpose()) 
  File "/usr/local/lib/python3.8/site-packages/scipy/io/mmio.py", line 101, in mmwrite
    MMFile().write(target, a, comment, field, precision, symmetry)
  File "/usr/local/lib/python3.8/site-packages/scipy/io/mmio.py", line 451, in write
    stream, close_it = self._open(target, 'wb')
  File "/usr/local/lib/python3.8/site-packages/scipy/io/mmio.py", line 323, in _open
    stream = open(filespec, mode)
OSError: [Errno 30] Read-only file system: './/matrix.mtx'
```

toolshed.g2.bx.psu.edu/repos/ebi-gxa/salmon_kallisto_mtx_to_10x/_salmon_kallisto_mtx_to_10x/0.0.1+galaxy5

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/ebi-gxa/salmon_kallisto_mtx_to_10x/_salmon_kallisto_mtx_to_10x/0.0.1+galaxy5

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary


|  State | Count |
| ---------- | ----- |
| Total      | 0 |
| Passed     | 0 |
| Error      | 0 |
| Failure    | 0 |
| Skipped    | 0 |

**Comment by jennaj** [comment]
No test case included in the tool
