### ISSUE TITLE
test alphafold 2.1.2+galaxy0

### ISSUE THREAD

**Issue by jennaj** [mvdbeek/usegalaxy-tests#47]
Tool missing reference data? Or, cluster hiccup? 

This is the only version of the tool at usegalaxy.org.
The server usegalaxy.eu has this 2.1.2+galaxy0 plus a newer version 2.1.2+galaxy1, but loads 2.1.2+galaxy0 from the tool panel.
No versions installed at usegalaxy.org.au.

> 0630 11:40:25.686394 47076058240896 hhsearch.py:56] Could not find HHsearch database /data/pdb70/pdb70
> Traceback (most recent call last):
> File "/app/alphafold/run_alphafold.py", line 445, in <module>
> app.run(main)
> File "/opt/conda/lib/python3.7/

toolshed.g2.bx.psu.edu/repos/galaxy-australia/alphafold2/alphafold/2.1.2+galaxy0

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/galaxy-australia/alphafold2/alphafold/2.1.2+galaxy0

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="1" data-toggle="tooltip" title="0 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="1" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 100.0%" aria-valuenow="1" aria-valuemin="0" aria-valuemax="1" title="1 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 1 |
| Passed     | 0 |
| Error      | 0 |
| Failure    | 1 |
| Skipped    | 0 |


<details><summary>Failed s</summary>

* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/galaxy-australia/alphafold2/alphafold (Test #1)</summary><div class="padded">

    **Problems**:
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/galaxy-australia/alphafold2/alphafold/2.1.2+galaxy0, exit_code: 1, stderr: E0630 13:10:49.958549 47746791745408 hhsearch.py:56] Could not find HHsearch database /data/pdb70/pdb70
      Traceback (most recent call last):
        File "/app/alphafold/run_alphafold.py", line 445, in <module>
          app.run(main)
        File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
          _run_main(main, args)
        File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
          sys.exit(main(argv))
        File "/app/alphafold/run_alphafold.py", line 353, in main
          databases=[FLAGS.pdb70_database_path])
        File "/app/alphafold/alphafold/data/tools/hhsearch.py", line 57, in __init__
          raise ValueError(f'Could not find HHsearch database {database_path}')
      ValueError: Could not find HHsearch database /data/pdb70/pdb70
      .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/galaxy-australia/alphafold2/alphafold/2.1.2+galaxy0, exit_code: 1, stderr: E0630 13:10:49.958549 47746791745408 hhsearch.py:56] Could not find HHsearch database /data/pdb70/pdb70
      Traceback (most recent call last):
        File "/app/alphafold/run_alphafold.py", line 445, in <module>
          app.run(main)
        File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
          _run_main(main, args)
        File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
          sys.exit(main(argv))
        File "/app/alphafold/run_alphafold.py", line 353, in main
          databases=[FLAGS.pdb70_database_path])
        File "/app/alphafold/alphafold/data/tools/hhsearch.py", line 57, in __init__
          raise ValueError(f'Could not find HHsearch database {database_path}')
      ValueError: Could not find HHsearch database /data/pdb70/pdb70
      .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/galaxy-australia/alphafold2/alphafold/2.1.2+galaxy0, exit_code: 1, stderr: E0630 13:10:49.958549 47746791745408 hhsearch.py:56] Could not find HHsearch database /data/pdb70/pdb70
      Traceback (most recent call last):
        File "/app/alphafold/run_alphafold.py", line 445, in <module>
          app.run(main)
        File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
          _run_main(main, args)
        File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
          sys.exit(main(argv))
        File "/app/alphafold/run_alphafold.py", line 353, in main
          databases=[FLAGS.pdb70_database_path])
        File "/app/alphafold/alphafold/data/tools/hhsearch.py", line 57, in __init__
          raise ValueError(f'Could not find HHsearch database {database_path}')
      ValueError: Could not find HHsearch database /data/pdb70/pdb70
      .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/galaxy-australia/alphafold2/alphafold/2.1.2+galaxy0, exit_code: 1, stderr: E0630 13:10:49.958549 47746791745408 hhsearch.py:56] Could not find HHsearch database /data/pdb70/pdb70
      Traceback (most recent call last):
        File "/app/alphafold/run_alphafold.py", line 445, in <module>
          app.run(main)
        File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
          _run_main(main, args)
        File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
          sys.exit(main(argv))
        File "/app/alphafold/run_alphafold.py", line 353, in main
          databases=[FLAGS.pdb70_database_path])
        File "/app/alphafold/alphafold/data/tools/hhsearch.py", line 57, in __init__
          raise ValueError(f'Could not find HHsearch database {database_path}')
      ValueError: Could not find HHsearch database /data/pdb70/pdb70
      .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/galaxy-australia/alphafold2/alphafold/2.1.2+galaxy0, exit_code: 1, stderr: E0630 13:10:49.958549 47746791745408 hhsearch.py:56] Could not find HHsearch database /data/pdb70/pdb70
      Traceback (most recent call last):
        File "/app/alphafold/run_alphafold.py", line 445, in <module>
          app.run(main)
        File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
          _run_main(main, args)
        File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
          sys.exit(main(argv))
        File "/app/alphafold/run_alphafold.py", line 353, in main
          databases=[FLAGS.pdb70_database_path])
        File "/app/alphafold/alphafold/data/tools/hhsearch.py", line 57, in __init__
          raise ValueError(f'Could not find HHsearch database {database_path}')
      ValueError: Could not find HHsearch database /data/pdb70/pdb70
      .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/galaxy-australia/alphafold2/alphafold/2.1.2+galaxy0, exit_code: 1, stderr: E0630 13:10:49.958549 47746791745408 hhsearch.py:56] Could not find HHsearch database /data/pdb70/pdb70
      Traceback (most recent call last):
        File "/app/alphafold/run_alphafold.py", line 445, in <module>
          app.run(main)
        File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
          _run_main(main, args)
        File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
          sys.exit(main(argv))
        File "/app/alphafold/run_alphafold.py", line 353, in main
          databases=[FLAGS.pdb70_database_path])
        File "/app/alphafold/alphafold/data/tools/hhsearch.py", line 57, in __init__
          raise ValueError(f'Could not find HHsearch database {database_path}')
      ValueError: Could not find HHsearch database /data/pdb70/pdb70
      .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/galaxy-australia/alphafold2/alphafold/2.1.2+galaxy0, exit_code: 1, stderr: E0630 13:10:49.958549 47746791745408 hhsearch.py:56] Could not find HHsearch database /data/pdb70/pdb70
      Traceback (most recent call last):
        File "/app/alphafold/run_alphafold.py", line 445, in <module>
          app.run(main)
        File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
          _run_main(main, args)
        File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
          sys.exit(main(argv))
        File "/app/alphafold/run_alphafold.py", line 353, in main
          databases=[FLAGS.pdb70_database_path])
        File "/app/alphafold/alphafold/data/tools/hhsearch.py", line 57, in __init__
          raise ValueError(f'Could not find HHsearch database {database_path}')
      ValueError: Could not find HHsearch database /data/pdb70/pdb70
      .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/galaxy-australia/alphafold2/alphafold/2.1.2+galaxy0, exit_code: 1, stderr: E0630 13:10:49.958549 47746791745408 hhsearch.py:56] Could not find HHsearch database /data/pdb70/pdb70
      Traceback (most recent call last):
        File "/app/alphafold/run_alphafold.py", line 445, in <module>
          app.run(main)
        File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
          _run_main(main, args)
        File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
          sys.exit(main(argv))
        File "/app/alphafold/run_alphafold.py", line 353, in main
          databases=[FLAGS.pdb70_database_path])
        File "/app/alphafold/alphafold/data/tools/hhsearch.py", line 57, in __init__
          raise ValueError(f'Could not find HHsearch database {database_path}')
      ValueError: Could not find HHsearch database /data/pdb70/pdb70
      .
      ```
    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      1
      ```
    **Standard Error:**

    * ```console
      E0630 13:10:49.958549 47746791745408 hhsearch.py:56] Could not find HHsearch database /data/pdb70/pdb70
      Traceback (most recent call last):
        File "/app/alphafold/run_alphafold.py", line 445, in <module>
          app.run(main)
        File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
          _run_main(main, args)
        File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
          sys.exit(main(argv))
        File "/app/alphafold/run_alphafold.py", line 353, in main
          databases=[FLAGS.pdb70_database_path])
        File "/app/alphafold/alphafold/data/tools/hhsearch.py", line 57, in __init__
          raise ValueError(f'Could not find HHsearch database {database_path}')
      ValueError: Could not find HHsearch database /data/pdb70/pdb70

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | fasta\_or\_text | ` {"__current_case__": 0, "fasta_file": {"values": [{"id": 99730529, "src": "hda"}]}, "input_mode": "history"} ` |
       | output\_plddts | ` "true" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


</details>

**Comment by pariskang** [comment]
I installed alphafold_non_docker step by step, but I found an error as the following:
```
(alphafold) [root@ecs alphafold-2.2.0]# bash run_alphafold.sh -d ./alphafold_data -o ./dummy_test/ -f ./example/query.fasta -t 2020-05-14 -g False
E0704 11:23:00.766234 139973713471296 hhsearch.py:56] Could not find HHsearch database ./alphafold_data//pdb70/pdb70
Traceback (most recent call last):
  File "/root/alphafold-2.2.0/run_alphafold.py", line 422, in <module>
    app.run(main)
  File "/root/miniconda3/envs/alphafold/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/root/miniconda3/envs/alphafold/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/root/alphafold-2.2.0/run_alphafold.py", line 327, in main
    template_searcher = hhsearch.HHSearch(
  File "/root/alphafold-2.2.0/alphafold/data/tools/hhsearch.py", line 57, in __init__
    raise ValueError(f'Could not find HHsearch database {database_path}')
ValueError: Could not find HHsearch database ./alphafold_data/pdb70/pdb70

```
How to resolve this problem, I sincerely need u help. Thank u~
